service: node-rest-mongoose

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  createPhoto:
    handler: handler.createPhoto
    events:
      - http:
          path: user/{id}/photo
          method: post
          cors: true

  updatePhoto:
    handler: handler.updatePhoto
    events:
      - http:
          path: user/{id}/photo/{_id}
          method: put
          cors: true

  photo:
    handler: handler.photo
    events:
      - http:
          path: user/{id}/photo/{_id}
          method: get
          cors: true

  createApproval:
    handler: handler.createUserApproval
    events:
      - http:
          path: user/{id}/approval
          method: post
          cors: true

  updateApproval:
    handler: handler.updateApproval
    events:
      - http:
          path: user/{id}/approval/{_id}
          method: put
          cors: true

  approval:
    handler: handler.approval
    events:
      - http:
          path: user/{id}/approval/{_id}
          method: get
          cors: true
